services:
  achtungkurve:
    build:
      context: ./frontend
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
    ports:
      - "3000:3000"
    command: ["npm", "run", "dev"]
    environment:
      - NODE_ENV=development

  echo:
    build:
      context: ./backend
    ports:
      - "3001:80"
