services:
  achtungkurve:
    build: .
    working_dir: /app
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    ports:
      - "3000:3000"  # Change this if your app runs on a different port
    command: ["npm", "run", "dev"]
    environment:
      - NODE_ENV=development